runtime: nodejs20
env: standard
entrypoint: npm start

instance_class: F2

env_variables:
  DB_USER: 'postgres'
  DB_PASSWORD: 'postgres'
  DB_NAME: 'e-commerce'
  INSTANCE_CONNECTION_NAME: 'nlu-gcp-hk241-group01:us-central1:cc-group02'
  DB_PORT: '5432'
  
  JWT_SECRET: 'ggcloud1234554321!@#'
  JWT_SECRET_ACCESS_TOKEN: 'ggcloud1234554321!@#'
  JWT_SECRET_REFRESH_TOKEN: 'ggcloud1234554321!@#@'
  JWT_SECRET_EMAIL_VERIFY_TOKEN: 'ggcloud1234554321!@#$#'
  JWT_SECRET_FORGOT_PASSWORD_TOKEN: 'ggcloud12344321!@#$#'
  
  EMAIL_VERIFY_TOKEN_EXPIRES_IN: '7d'
  ACCESS_TOKEN_EXPIRES_IN: '15m'
  REFRESH_TOKEN_EXPIRES_IN: '100d'

handlers:
  - url: /.*  
    script: auto
